### ISSUE TITLE
Fatal error: Class 'Dotenv\Dotenv' not found in ACFProInstaller/Plugin.php

### ISSUE THREAD

**Issue by davidohlin** [RegionHalland/wordpress-boilerplate#2]
When running `vagrant provision` for the first time Composer fails to install ACF with the following error:

```
PHP Fatal error:  Uncaught Error: Class 'Dotenv\Dotenv' not found in /srv/www/nyheter.test/current/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php:246
Stack trace:
#0 /srv/www/nyheter.test/current/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php(226): PhilippBaschke\ACFProInstaller\Plugin->loadDotEnv()
#1 /srv/www/nyheter.test/current/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php(144): PhilippBaschke\ACFProInstaller\Plugin->getKeyFromEnv()
#2 [internal function]: PhilippBaschke\ACFProInstaller\Plugin->addKey(Object(Composer\Plugin\PreFileDownloadEvent))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Plugin\PreFileDownloadEvent))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(81): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Plugin\PreFileDownloadEvent))
#5 phar:///usr/local/bin/composer/src/Composer/Downloader/FileDownlo in /srv/www/nyheter.test/current/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php on line 246

Fatal error: Uncaught Error: Class 'Dotenv\Dotenv' not found in /srv/www/nyheter.test/current/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php:246
Stack trace:
#0 /srv/www/nyheter.test/current/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php(226): PhilippBaschke\ACFProInstaller\Plugin->loadDotEnv()
#1 /srv/www/nyheter.test/current/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php(144): PhilippBaschke\ACFProInstaller\Plugin->getKeyFromEnv()
#2 [internal function]: PhilippBaschke\ACFProInstaller\Plugin->addKey(Object(Composer\Plugin\PreFileDownloadEvent))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Plugin\PreFileDownloadEvent))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(81): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Plugin\PreFileDownloadEvent))
#5 phar:///usr/local/bin/composer/src/Composer/Downloader/FileDownlo in /srv/www/nyheter.test/current/vendor/philippbaschke/acf-pro-installer/src/ACFProInstaller/Plugin.php on line 246
```

The solution right now is to delete `./site/vendor/`, run `composer update` and `composer install`. Roots claims this error is fixed in Composer 1.6.2, but that doesn't seem to be true ¯\_(ツ)_/¯

* https://github.com/PhilippBaschke/acf-pro-installer/issues/21
* https://discourse.roots.io/t/php-fatal-error-uncaught-error-class-dotenv-dotenv-not-found/11241/10
* https://stackoverflow.com/questions/37199237/fatal-error-class-dotenv-dotenv-not-found-in

**Comment by davidohlin** [comment]
ACF installer when deploying gets the same problem when deploying for the first time. Follow [these instructions](https://github.com/iff-studio/acf-pro-installer/issues/1) for a temporary fix.
